from django.urls import path
from . import views


urlpatterns=[
    path('',views.index,name='index'),
    path('about/', views.about,name='about'),
    path('contact/',views.contact,name='contact'),
    path('login/',views.login,name='login'),
    path('enquiry/',views.enquiry,name='enquiry'),
    path('logcode/',views.logcode,name='logcode'),
    path('organization/', views.organization,name='organization'),
    path('biotechpark/', views.biotechpark,name='biotechpark'),
    path('locations/', views.locations,name='locations'),
    path('certifications/', views.certifications,name='certifications'),
    path('ourcollab/', views.ourcollab,name='ourcollab'),
    path('knowledge/', views.knowledge,name='knowledge'),
    path('outreach/', views.outreach,name='outreach'),
    path('ceo/', views.ceo,name='ceo'),
    path('distinguished/', views.distinguished,name='distinguished'),
    path('scientificstaff/', views.scientificstaff,name='scientificstaff'),
    path('administration/', views.administration,name='administration'),
    path('technicalsupport/', views.technicalsupport,name='technicalsupport'),
    path('adminlayout/',views.adminlayout,name='adminlayout'),
    path('showenquiry/',views.showenquiry,name='showenquiry'),
    path('addsession/',views.addsession,name='addsession'),
    path('assave/',views.assave,name='assave'),
    path('addcourse/',views.addcourse,name="addcourse"),
    path('delsession/<id>',views.delsession,name='delsession'),
    path('viewcousre/',views.viewcourse,name='viewcourse'),
    path('delcourse/<id>',views.delcourse,name='delcourse'),
    path('viewsession/',views.viewsession,name='viewsession'),
    path('delenq/<id>',views.delenq,name='delenq'),
    path('editsession/<id>',views.editsession,name='editsession'),
    path('updatesession/',views.updatesession,name='updatesession'),
    path('editcourse/<id>', views.editcourse,name='editcourse'),
    path('updatecourse/',views.updatecourse,name='updatecourse'),
    path('addstudent/',views.addstudent,name='addstudent'),
    path('studentdash/',views.studentdash,name='studentdash'),
    path('stdapplication/',views.stdapplication,name='stdapplication'),
    path('saveinfo/',views.saveinfo,name='saveinfo'),
    path('uploaddoc/',views.uploaddoc,name='uploaddoc'),
    path('verifydoc/',views.verifydoc,name='verifydoc'),
    path('editstudent/<sid>',views.editstudent,name='editstudent'),
    path('viewstudent/',views.viewstudent,name='viewstudent'),
    path('updatestudent/',views.updatestudent,name='updatestudent'),
    path('delstudent/<sid>',views.delstudent,name='delstudent'),
    path('verifystu/<sid>',views.verifystu,name='verifystu'),
    path('payfees/',views.payfees,name='payfees'),
    path('finalsubmit/',views.finalsubmit,name='finalsubmit'),
    path('finalverification/',views.finalverification,name='finalverification'),
    path('assign/<id>',views.assign,name='assign'),
    path('finalstudents/',views.finalstudents,name='finalstudents'),
    path('logout/',views.logout,name='logout'),
    path('changepass/',views.changepass,name='changepass'),
    path('changesave/',views.changesave,name='changesave'),
    path('changepassadmin/',views.changepassadmin,name='changepassadmin'),
    path('changesaveadmin/',views.changesaveadmin,name='changesaveadmin'),
    path('admindash/',views.admindash,name='admindash'),


]