# Generated by Django 5.1 on 2024-09-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oasapp', '0002_adminlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('session', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField()),
            ],
        ),
    ]
