# Generated by Django 5.1 on 2024-09-15 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oasapp', '0007_student_alter_enquiry_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
